name: Deploy Node.js with TypeScript on EC2

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.15"
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Install TypeScript Compiler
        run: npm install -g typescript
      - name: Build Project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.15"
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Build Project
        run: npm run build
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure NVM is sourced on EC2
        run: |
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            # Source NVM so Node.js and npm work
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads NVM
            nvm use 22.14.0  # Ensure the correct Node.js version is used
          EOF

      - name: Deploy Backend to EC2
        env:
          EC2_HOST: ${{ secrets.SERVER_HOST }}
          EC2_USER: ${{ secrets.SERVER_USER }}
          ENV_VARS_JSON: ${{ secrets.ENV_VARS_JSON }}
        run: |
          ssh $EC2_USER@$EC2_HOST "mkdir -p ~/applications/backend"
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='.github' . $EC2_USER@$EC2_HOST:~/applications/backend/
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            # Ensure the environment is loaded and install dependencies
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads NVM
            nvm use 22.14.0  # Ensure the correct Node.js version is used
            cd ~/applications/backend && npm install --frozen-lockfile --production
          EOF
          ssh $EC2_USER@$EC2_HOST "echo '$ENV_VARS_JSON' > ~/applications/backend/.env"
          ssh $EC2_USER@$EC2_HOST "pm2 delete backend || true"
          ssh $EC2_USER@$EC2_HOST "cd ~/applications/backend && pm2 start dist/server.js --name backend"

# name: Deploy Node.js with TypeScript on EC2

# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - "main"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "20.15"

#       - name: Install Dependencies
#         run: npm install --frozen-lockfile

#       - name: Install TypeScript Compiler
#         run: npm install -g typescript

#       - name: Build Project
#         run: npm run build

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "20.15"

#       - name: Install Dependencies
#         run: npm install --frozen-lockfile

#       - name: Build Project
#         run: npm run build

#       - name: Configure SSH
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#         run: |
#           mkdir -p ~/.ssh
#           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

#       - name: Deploy to EC2
#         env:
#           EC2_HOST: ${{ secrets.SERVER_HOST }}
#           EC2_USER: ${{ secrets.SERVER_USER }}
#           ENV_VARS_JSON: ${{ secrets.ENV_VARS_JSON }}
#         run: |
#           ssh $EC2_USER@$EC2_HOST "mkdir -p ~/server"
#           rsync -avz \
#             --exclude='.git' \
#             --exclude='node_modules' \
#             --exclude='.github' \
#             . $EC2_USER@$EC2_HOST:~/server/
#           ssh $EC2_USER@$EC2_HOST "cd ~/server && npm install --frozen-lockfile --production"
#           ssh $EC2_USER@$EC2_HOST "echo '$ENV_VARS_JSON' > ~/server/.env"
#           ssh $EC2_USER@$EC2_HOST "pm2 delete nodejs-server || true"
#           ssh $EC2_USER@$EC2_HOST "cd ~/server && pm2 start dist/index.js --name nodejs-server"
